### ISSUE TITLE
Oplossing drie koloms layout

### ISSUE THREAD

**Issue by Stefan-Espant** [kosterm14/lets-jam-webapplicatie#77]
Dit is de oplossing voor een drie koloms layout voor desktop

```css
@media screen and (min-width: 1280px) {
  section {
    grid-template-columns: 1fr 1fr 1fr;
  }
 ```
 
 Tip:
 Geef een waarde van 30rem mee om ervoor te zorgen dat je tussen de 11 & 13 woorden per zin blijft. Zo blijft die voor iedereen toegankelijk.
